# Generated by Django 4.2 on 2023-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_account_user_id_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cheque_book',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_card',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='debit_card',
            field=models.BooleanField(default=0),
        ),
    ]
